#!/usr/bin/env python3
"""Step 8 retrieval ablation (plan step 8): filesystem-only vs. graph-first vs.
hybrid navigation, on the cheap `smoke` cohort (4 tasks), proxy-model fidelity.

Three submission variants live under
devtools/retrieval_ablation/variants/<variant>/ (built once by hand,
not regenerated by this script):
  - hybrid: byte-identical copy of the current submission/ (all 9 tools,
    unmodified prompt) — the control arm, i.e. what's actually shipping today.
  - filesystem-only: agent.yaml drops the 3 graph tools (get_code_neighbors,
    search_similar_code, get_code_subgraph); prompt/skill mentions of those
    tools removed so the prompt doesn't advertise tools the agent can't call.
  - graph-first: all 9 tools, but "Locating Target Files" in the prompt makes
    a graph-tool call (search_similar_code / get_code_neighbors) mandatory
    before the first read_file/grep, whenever a symbol is extractable.

The harness auto-injects a "Code Intelligence Tools" prompt section whenever
pre-computed graph/embedding data exists for task.repo, INDEPENDENT of
agent.yaml's declared tools (see swegemma.config.EvalConfig.graph_dir
auto-detection: defaults to 'data/graphs' and falls back to
<tasks_path's dir>/graphs only if 'data/graphs' does not exist relative to
the process's cwd). For the filesystem-only arm this would misleadingly
advertise tools the agent can't actually call, so those runs execute with
cwd=fs_only_cwd/ (which has empty data/graphs, data/embeddings dirs — makes
the 'data/graphs' existence check pass, skipping the fallback, leaving
graph_dir pointed at an empty directory). Verified empirically before this
script was written: build_agent_prompt() with cwd=repo root includes "Code
Intelligence Tools"; with cwd=fs_only_cwd it does not.

Usage:
    python3 devtools/run_retrieval_ablation.py [--dry-run]
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent.parent
VARIANTS_DIR = REPO_DIR / "devtools" / "retrieval_ablation" / "variants"
FS_ONLY_CWD = REPO_DIR / "devtools" / "retrieval_ablation" / "fs_only_cwd"
RUN_EVALUATION = REPO_DIR / "devtools" / "mlflow" / "run_evaluation.py"
MODELS_YAML = REPO_DIR / "devtools" / "models-ollama-e4b.yaml"

SMOKE_TASK_IDS = ["fastapi_15661", "requests_7505", "rich_4070", "httpx_3672"]
VARIANTS = ["hybrid", "filesystem-only", "graph-first"]

# Same generous budget for every run — the one thing that must stay identical
# across arms for the comparison to be fair.
MAX_TIME_MINUTES = "10"
MAX_TOOL_CALLS = "25"
MAX_TURNS = "15"

HYPOTHESES = {
    "hybrid": "Control arm: current shipping submission/ unchanged (all 9 tools, current prompt).",
    "filesystem-only": "Graph tools removed from agent.yaml + prompt/skill mentions stripped. Does removing "
                        "graph-tool availability change tool-calls-before-first-file-open, redundant-read rate, "
                        "or navigation time vs. hybrid?",
    "graph-first": "All 9 tools kept, but 'Locating Target Files' now mandates a graph-tool call "
                   "(search_similar_code/get_code_neighbors) before the first read_file/grep whenever a symbol "
                   "is extractable. Does forcing graph-first navigation reduce tool-calls-before-first-file-open "
                   "vs. hybrid, or just add an extra call that doesn't pay for itself?",
}


def run_one(variant: str, task_id: str, dry_run: bool) -> int:
    label = f"2026-09-29_step8-retrieval-{variant}-{task_id}"
    submission_dir = VARIANTS_DIR / variant
    cwd = FS_ONLY_CWD if variant == "filesystem-only" else REPO_DIR

    cmd = [
        sys.executable, str(RUN_EVALUATION),
        "--label", label,
        "--submission-dir", str(submission_dir),
        "--task-ids", task_id,
        "--sandbox", "docker",
        "--max-time-minutes", MAX_TIME_MINUTES,
        "--max-tool-calls", MAX_TOOL_CALLS,
        "--max-turns", MAX_TURNS,
        "--models-yaml", str(MODELS_YAML),
        "--backend", "stand-in-e4b",
        "--env", "local-mac",
        "--fidelity", "proxy-model",
        "--cohort", "smoke",
        "--hypothesis", f"Step 8 retrieval ablation [{variant}] on {task_id}: {HYPOTHESES[variant]}",
    ]

    print(f"\n=== {label} (cwd={cwd}) ===", flush=True)
    print(" ".join(cmd), flush=True)
    if dry_run:
        return 0
    proc = subprocess.run(cmd, cwd=str(cwd))
    return proc.returncode


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--dry-run", action="store_true", help="Print commands without running them")
    p.add_argument("--only-variant", choices=VARIANTS, default=None)
    p.add_argument("--only-task", choices=SMOKE_TASK_IDS, default=None)
    args = p.parse_args()

    variants = [args.only_variant] if args.only_variant else VARIANTS
    task_ids = [args.only_task] if args.only_task else SMOKE_TASK_IDS

    failures = []
    for variant in variants:
        for task_id in task_ids:
            rc = run_one(variant, task_id, args.dry_run)
            if rc != 0:
                failures.append((variant, task_id, rc))

    if failures:
        print(f"\n{len(failures)} run(s) failed:", file=sys.stderr)
        for variant, task_id, rc in failures:
            print(f"  {variant}/{task_id}: exit {rc}", file=sys.stderr)
        return 1
    print("\nAll runs completed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
